### ISSUE TITLE
Application Crash while using registerPushNotification() function.

### ISSUE THREAD

**Issue by SanketDorle** [AppLozic/Applozic-Cordova-PhoneGap-Chat-Plugin#9]
From login success callback, call applozic.registerPushNotification(function() {}, function(){});

I Have an Error 
Error Log:

`06-20 14:12:16.716 32501-32635/com.snt.egrand E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
                                                                Process: com.snt.egrand, PID: 32501
                                                                java.lang.AbstractMethodError: abstract method "void com.google.firebase.iid.zzb.handleIntent(android.content.Intent)"
                                                                    at com.google.firebase.iid.zzb$1.run(Unknown Source)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                    at java.lang.Thread.run(Thread.java:818)`

Sample Code : 

var alUser = {

                'userId': <applozic_user_id>,   //Replace it with the userId of the logged in user

                'password': <password>,  //Put password here

                'authenticationTypeId': 1,

                'applicationId': <application id>,

                'deviceApnsType': 0    //Set 0 for Development and 1 for Distribution (Release)s

            };

            applozic.login(alUser, function () {

                applozic.registerPushNotification(function () {

                    console.log('registerPushNotification success');

                }, function (error) {

                    console.log('registerPushNotification error');

                   console.log(error);

                });

            }, function () {});

**Comment by devashishmamgain** [comment]
Can you check firebase library versions in your build.gradle file
https://stackoverflow.com/a/43111374/1122828

Please attach a sample project code to reproduce the issue.

**Comment by SanketDorle** [comment]
there is no firebase library versions in my build.gradle file

please find attachment.


[build.gradle.zip](https://github.com/AppLozic/Applozic-Cordova-PhoneGap-Chat-Plugin/files/1114350/build.gradle.zip)

**Comment by devashishmamgain** [comment]
can replacing the following in build.gradle
  compile "com.google.android.gms:play-services-gcm:10.2+"
with
    compile "com.google.android.gms:play-services-gcm:10.0.1"

**Comment by devashishmamgain** [comment]
@SanketDorle is it working now? Can i close the issue.

**Comment by SanketDorle** [comment]
**issue fixed.** 
The Problem actual is in Push notification pulgin. I just remove that plugin and its work fine.
